# Makefile for multi_proc_pmu + TACLeBench kernel benches
#
# Build flow per bench <name>:
#   1. Compile every .c in bench/bench/kernel/<name>/ into a private .o under
#      build/<name>/, with -Dmain=<name>_main_disabled to neutralize the bench's
#      own int main().
#   2. Combine those into a relocatable build/<name>.combined.o via `ld -r`.
#   3. Run objcopy --keep-global-symbol=<name>_{init,main,return} so every
#      other symbol becomes local to that single .o. This isolates each bench
#      and prevents cross-bench symbol collisions (e.g. cosf/cubic/isqrt all
#      ship identical copies of wcclibm.c).
#   4. Auto-generate build/bench_registry.h listing all discovered benches.
#   5. Final link merges multi_proc_pmu.o with all per-bench .o files.

CC      ?= gcc
LD      ?= ld
OBJCOPY ?= objcopy
CFLAGS  ?= -O0 -g -Wall -Wno-unused-result -Wno-unknown-pragmas -std=gnu11
LDFLAGS ?=

BENCH_ROOT := bench/bench
BUILD_DIR  := build

# Bench categories to include. We deliberately skip `parallel/` because those
# benches (DEBIE, PapaBench, rosace) ship multi-thread / multi-arch source
# trees that don't fit the simple per-bench `<name>_{init,main,return}` API
# this harness expects, and they pull in arch-specific code (arm7, mpc5554,
# tc1797) that would not compile on a generic x86_64 Linux host.
BENCH_CATEGORIES := kernel app sequential test TIM POLY MTH

# Auto-discover every bench directory across the selected categories.
BENCH_DIRS := $(sort $(wildcard $(addprefix $(BENCH_ROOT)/,$(addsuffix /*/,$(BENCH_CATEGORIES)))))
BENCHES    := $(sort $(notdir $(patsubst %/,%,$(BENCH_DIRS))))

# Map bench-name -> source-dir (used inside BENCH_TEMPLATE).
$(foreach d,$(BENCH_DIRS),$(eval BENCH_SRCDIR_$(notdir $(patsubst %/,%,$(d))) := $(patsubst %/,%,$(d))))

BENCH_OBJS := $(addprefix $(BUILD_DIR)/,$(addsuffix .o,$(BENCHES)))
REGISTRY_H := $(BUILD_DIR)/bench_registry.h

TARGET := multi_proc_pmu
OBJS   := multi_proc_pmu.o $(BENCH_OBJS)

.PHONY: all clean list-benches
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

multi_proc_pmu.o: multi_proc_pmu.c $(REGISTRY_H)
	$(CC) $(CFLAGS) -I$(BUILD_DIR) -c -o $@ $<

$(REGISTRY_H): Makefile
	@mkdir -p $(@D)
	@echo "/* auto-generated by Makefile; do not edit */"          >  $@
	@echo "#ifndef BENCH_REGISTRY_H"                               >> $@
	@echo "#define BENCH_REGISTRY_H"                               >> $@
	@echo "#define BENCH_LIST(X) \\"                               >> $@
	@for b in $(BENCHES); do printf '    X(%s) \\\n' "$$b" >> $@; done
	@echo ""                                                       >> $@
	@echo "#endif"                                                 >> $@

# --- Per-bench template ----------------------------------------------------

# $(1) = bench name; $$(BENCH_SRCDIR_$(1)) = absolute-ish source dir.
define BENCH_TEMPLATE
$(1)_SRCDIR := $$(BENCH_SRCDIR_$(1))
$(1)_SRCS   := $$(wildcard $$($(1)_SRCDIR)/*.c)
$(1)_OBJS   := $$(patsubst $$($(1)_SRCDIR)/%.c,$$(BUILD_DIR)/$(1)/%.o,$$($(1)_SRCS))

$$(BUILD_DIR)/$(1)/%.o: $$($(1)_SRCDIR)/%.c
	@mkdir -p $$(@D)
	$$(CC) $$(CFLAGS) -Dmain=$(1)_main_disabled -c -o $$@ $$<

$$(BUILD_DIR)/$(1).o: $$($(1)_OBJS)
	@mkdir -p $$(@D)
	$$(LD) -r -o $$@.tmp $$^
	$$(OBJCOPY) \
	    --keep-global-symbol=$(1)_init \
	    --keep-global-symbol=$(1)_main \
	    --keep-global-symbol=$(1)_return \
	    $$@.tmp $$@
	@rm -f $$@.tmp
endef

$(foreach b,$(BENCHES),$(eval $(call BENCH_TEMPLATE,$(b))))

list-benches:
	@echo $(BENCHES)

clean:
	rm -rf $(BUILD_DIR) $(TARGET) multi_proc_pmu.o
